apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    # This is the default in this team's clusters. Stated explicitly here
    # so it is impossible to misread.
    istio-injection: enabled
