apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-api
  namespace: wiki
  labels:
    app: wiki-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-api
  template:
    metadata:
      labels:
        app: wiki-api
        workspace.io/ext-authz: enabled
    spec:
      containers:
      - name: wiki-api
        image: workspace/echo-server:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests: { cpu: 50m, memory: 64Mi }
          limits:   { cpu: 200m, memory: 128Mi }
        readinessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 5
